name: "word_3langs_train_bam_fr_transformer"

data:
    # bam_fr_bpe
    src: "bamfrens"
    trg: "bamfrent"
    train: "data/train"
    dev:   "data/dev"
    test:  "data/test"
    level: "word"
    lowercase: False
    max_sent_length: 100
    #src_vocab: "shared_models/vocab.bam"
    #trg_vocab: "shared_models/vocab.fr"
    src_voc_min_freq: 0
    src_voc_limit: 1000
    trg_voc_min_freq: 0
    trg_voc_limit: 1000

testing:
    beam_size: 5  #AAT: try out up or down [0-10]
    alpha: 1.0

training:
    # AAT: use here when it's time to translate
    #load_model: "{gdrive_path}/models/{name}_transformer/1.ckpt" # if uncommented, load a pre-trained model from this checkpoint
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"           #  AAT: maybe comment out ... TODO: try switching from plateau to Noam scheduling
    patience: 5                     # AAT: maybe increase ... For plateau: decrease learning rate by decrease_factor if validation score has not improved for this many validation rounds.
    learning_rate_factor: 0.5       # factor for Noam scheduler (used with Transformer)
    learning_rate_warmup: 1000      # warmup steps for Noam scheduler (used with Transformer)
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0004
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.2    # AAT: from 0.1 to 0.2 (maybe change to increase)
    batch_size: 1024    # AAT: change batch size, maybe half of actual, smaller < 1000 (maybe 200) specially when you run out of memory
    batch_type: "token"   # AAT: does not need to change or change to unit
    eval_batch_size: 256   # AAT: when you run out of memory, check here 1st and 64 when using sentence level
    eval_batch_type: "token"  # AAT: does not need to change or change to unit
    batch_multiplier: 1
    early_stopping_metric: "eval_metric"    # AAT: from ppl to eval_metric
    epochs: 120                     # TODO: Decrease for when playing around and checking of working. Around 30 is sufficient to check if its working at all
    validation_freq: 40          # AAT: maybe increase ... TODO: Set to at least once per epoch.
    logging_freq: 10
    eval_metric: "bleu"
    model_dir: "models/bam_to_fr_bpe_transformer"
    overwrite: True               # TODO: Set to True if you want to overwrite possibly existing models.
    shuffle: True
    use_cuda: True
    max_output_length: 528
    print_valid_sents: [0, 1, 2, 3]
    keep_last_ckpts: 3

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_embeddings: False
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4             # TODO: Increase to 8 for larger data.
        embeddings:
            embedding_dim: 256   # TODO: Increase to 512 for larger data.
            scale: True
            dropout: 0.2
        # typically ff_size = 4 x hidden_size
        hidden_size: 256         # TODO: Increase to 512 for larger data.
        ff_size: 1024            # TODO: Increase to 2048 for larger data.
        dropout: 0.3
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4              # TODO: Increase to 8 for larger data.
        embeddings:
            embedding_dim: 256    # TODO: Increase to 512 for larger data.
            scale: True
            dropout: 0.2
        # typically ff_size = 4 x hidden_size
        hidden_size: 256         # TODO: Increase to 512 for larger data.
        ff_size: 1024            # TODO: Increase to 2048 for larger data.
        dropout: 0.3
